### PR TITLE
Ft register-driver/user 158322668

### PR DESCRIPTION
**Pull request by DerKip**
### What does this PR do?
    Gives a users an option to register as driver or normal user(passenger)
### Description of Tasks completed
- Create and "stylize" driver and user *buttons*
- add Event handler to displsy respective forms on click
### How should this be manually tested?
click on this link to preview 
https://derkip.github.io/Ride-My-Way/UI/index.html
- Click *Register*

#### Relevant pivotal tracker story
[#158322668](https://www.pivotaltracker.com/n/projects/2177670/stories/158322668)

### CODE REVIEW

**Comment by pngg** [comment]
Very clean and beautiful interface. Looks great!

**Comment by wandesky** [comment]
The github pages you have posted links to the homepage and not the ride offers page.

**Comment by DerKip** [comment]
@wandesky thanks, I noticed I did a PR on the wrong branch, but still, it contains this feature,
thanks for the review @pngg

**Comment by meshack-mbuvi** [comment]
The UI is good

**Pull request closed without merging**
