### PR TITLE
Ft create failing tests 158423893

### PR DESCRIPTION
**Pull request by DerKip**
### What does this PR do?
 Creates failing tests 
### Description of Tasks completed
- Test GET all ride offers
- Test GET ride offer by ID
- Test create ride offer
- Test user can make a request to join a ride offer
- Test Login and Registration

### How should this be manually tested?
~~~~
clone this repo
then checkout  ft create-failing-tests-158423893
on the terminal type pytest tests
~~~~

#### Relevant pivotal tracker story
[#158423893](https://www.pivotaltracker.com/story/show/158423893)

#### ScreenShot
failing

### CODE REVIEW

**Comment by Derrickkip** [comment]
Your approach to TDD is different, the way I understood it You write failing tests for a single feature then write code to make that feature pass before repeating the process with the next feature

**Comment by Dygn** [comment]
Good job on the tests...use pytest instead of unittest

**Comment by naibor** [comment]
nice.

**Comment by naibor** [comment]
@Dygn what do you mean use pytest instead of unittest?

**Comment by Dygn** [comment]
That's the testing framework for this assignment

**Comment by naibor** [comment]
https://docs.pytest.org/en/latest/unittest.html
you can have both.

**Comment by DerKip** [comment]
@Derrickkip  I get you, that's how it should, in this case, I've done basic tests (very basic) for the API,  asserting if the response status codes are equal to the tests status codes. Later on, as work on the feature, I'll be adding more  detailed, precise functional tests for the features

**Comment by DerKip** [comment]
The unittest module provides tools for constructing tests. I've used pytest to execute my tests @Dygn 
``` $ pytest tests```

**Comment by DerKip** [comment]
@Derrickkip, @Dygn, @naibor  Thank you for your reviews

**Pull request merged**
